# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'CommonToolsExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for CommonToolsExample
   pod 'SwiftCommonTools2', :path => '../' 
end
